const headers={"Content-Type":"application/json","Access-Control-Allow-Origin":"*"};
const executive=/(country manager|general manager|managing director|vp sales|vice president sales|head of sales|sales director|commercial director|chief revenue|cro\b|chief commercial|business director|director of sales|head of partnerships|partnerships director|regional director|country lead|gm france|directeur commercial|directeur général|responsable france)/i;
const relevantSector=/(media|advertis|adtech|martech|internet|digital|saas|marketplace|ecommerce|e-commerce|tech|software|platform|retail media|creator|travel|automotive|mobility|fintech|ai\b)/i;
function clean(x=''){return String(x).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
function score(j){let s=35;const text=[j.title,j.description,j.tags?.join(' '),j.company].join(' ');if(executive.test(j.title))s+=38;if(relevantSector.test(text))s+=18;if(/france|paris/i.test(j.location))s+=8;if(/remote|europe/i.test(j.location))s+=4;if(/sales|revenue|commercial|partnership/i.test(j.title))s+=8;return Math.min(100,s)}
function reasons(j){const r=[];if(executive.test(j.title))r.push('Niveau de séniorité cohérent');if(relevantSector.test([j.title,j.description,j.company].join(' ')))r.push('Secteur média/tech/internet');if(/france|paris/i.test(j.location))r.push('Périmètre France');if(/sales|revenue|commercial/i.test(j.title))r.push('Leadership commercial');return r.slice(0,4)}
async function arbeit(){const r=await fetch('https://www.arbeitnow.com/api/job-board-api');if(!r.ok)return[];const d=await r.json();return(d.data||[]).map(x=>({id:'arbeit-'+x.slug,title:x.title,company:x.company_name,location:x.location||'',remote:!!x.remote,url:x.url,description:clean(x.description).slice(0,800),tags:x.tags||[],source:'Arbeitnow',published:x.created_at||''}))}
async function remotive(){const r=await fetch('https://remotive.com/api/remote-jobs?category=sales-business');if(!r.ok)return[];const d=await r.json();return(d.jobs||[]).map(x=>({id:'remotive-'+x.id,title:x.title,company:x.company_name,location:x.candidate_required_location||'Remote',remote:true,url:x.url,description:clean(x.description).slice(0,800),tags:[x.category,x.job_type],source:'Remotive',published:x.publication_date||''}))}
exports.handler=async(event)=>{if(event.httpMethod==='OPTIONS')return{statusCode:204,headers,body:''};try{const all=(await Promise.allSettled([arbeit(),remotive()])).flatMap(x=>x.status==='fulfilled'?x.value:[]);const dedup=new Map();for(const j of all){j.score=score(j);j.reasons=reasons(j);if(j.score>=60)dedup.set((j.company+'|'+j.title).toLowerCase(),j)}const jobs=[...dedup.values()].sort((a,b)=>b.score-a.score).slice(0,150);return{statusCode:200,headers,body:JSON.stringify({jobs,updatedAt:new Date().toISOString(),sources:['Arbeitnow','Remotive']})}}catch(e){console.error(e);return{statusCode:500,headers,body:JSON.stringify({error:'Recherche d’opportunités impossible'})}}};
